"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CheckCircle2, FileCheck2, Fingerprint, LockKeyhole, Menu, Network, ShieldCheck, UploadCloud, X, Sparkles, PenLine, ScanSearch, FileText } from "lucide-react";
import { AzaeronMark } from "@/components/design-system";

const products = [
  { name: "Azaeron AI", icon: Sparkles, description: "A place for your questions, documents and conversations.", state: "Generation awaiting model approval" },
  { name: "AI Humaniser", icon: PenLine, description: "Review edits with your meaning and facts in view.", state: "Editorial suggestions available" },
  { name: "AI Detector", icon: ScanSearch, description: "Explore writing signals with clear uncertainty.", state: "Experimental · no authorship verdict" },
  { name: "Plagiarism Checker", icon: FileCheck2, description: "Trace matching passages to available sources.", state: "Workspace comparison" },
  { name: "Documents", icon: FileText, description: "Keep drafts, versions and evidence in one place.", state: "Private document workspace" },
];

export default function LandingPage() {
  const [mobileMenu, setMobileMenu] = useState(false);
  return <main className="azaeron-shell">
    <header className="public-nav"><div className="nav-inner"><Link href="/" className="brand-lockup" aria-label="Azaeron home"><AzaeronMark /></Link><button className="mobile-menu-button" onClick={() => setMobileMenu((open) => !open)} aria-expanded={mobileMenu} aria-controls="public-navigation" aria-label={mobileMenu ? "Close navigation" : "Open navigation"}>{mobileMenu ? <X size={19} /> : <Menu size={19} />}</button><nav id="public-navigation" className={`public-links ${mobileMenu ? "is-open" : ""}`} aria-label="Public navigation"><a href="#product" onClick={() => setMobileMenu(false)}>Product</a><a href="#method" onClick={() => setMobileMenu(false)}>Method</a><a href="#principles" onClick={() => setMobileMenu(false)}>Principles</a><Link href="/login">Sign in</Link><Link href="/register" className="nav-cta">Create workspace <ArrowRight size={14} /></Link></nav></div></header>
    <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Evidence-first writing intelligence <span className="eyebrow-version">VERITY</span></div><h1>Your words.<br />With <em>clarity.</em></h1><p className="hero-lede">A considered workspace for writing, reviewing and understanding your documents. Keep your voice. See the evidence. Stay in control.</p><div className="hero-actions"><Link className="button button-primary" href="/register">Create a workspace <ArrowRight size={16} /></Link><Link className="button button-quiet" href="#method">See how it works <ArrowRight size={16} /></Link></div><div className="trust-line"><span><LockKeyhole size={14} /> workspace scoped</span><span><FileCheck2 size={14} /> evidence linked</span><span><Fingerprint size={14} /> version aware</span></div></div><div className="hero-art" aria-label="Evidence-first workspace preview"><div className="hero-art-grid" /><div className="hero-art-label"><span className="live-dot" /> WORKSPACE PREVIEW <span>WORKFLOW OVERVIEW</span></div><div className="hero-score-card"><div className="score-card-top"><span>Analysis report</span><span className="score-status">EVIDENCE FIRST</span></div><div className="hero-preview-title">From first draft to a considered final word.</div><div className="hero-score-track" aria-hidden="true" /><div className="score-card-foot"><span>Every revision stays reviewable</span><strong>Reviewable</strong></div></div><div className="hero-float-card float-left"><Network size={16} /><span><strong>Versions</strong> preserved</span></div><div className="hero-float-card float-right"><CheckCircle2 size={15} /><span><strong>Changes</strong> reviewed</span></div><div className="hero-art-footer"><span>01</span><span>VERSION</span><i /><span>04</span><span>EVIDENCE</span></div></div></section>
    <section className="workspace-section" id="product"><div className="section-kicker"><span>01</span> The workspace <i /></div><div className="section-heading-row"><div><h2>Five tools. A clearer way to work.</h2><p>Move from a draft to a thoughtful review, without losing the thread.</p></div><div className="privacy-badge"><LockKeyhole size={15} /> Your workspace. Your documents.</div></div><div className="public-product-grid">{products.map(({ name, icon: Icon, description, state }, index) => <article key={name} className="public-product"><div className="flex items-center justify-between"><Icon size={23} aria-hidden="true" /><span className="text-xs text-slate-500">0{index + 1}</span></div><h3>{name}</h3><p>{description}</p><span className="public-product-state">{state}</span><Link href="/register" aria-label={`Explore ${name}`}>Explore workspace <ArrowRight size={15} aria-hidden="true" /></Link></article>)}</div><div className="public-scope"><ShieldCheck size={19} aria-hidden="true" /><p>Generative AI requires approved private models and is currently unavailable. Writing signals are experimental. Similarity shows overlap with the available corpus, not a plagiarism determination.</p></div></section>
    <section className="method-section" id="method"><div className="section-kicker"><span>02</span> The method <i /></div><div className="method-heading"><h2>Make progress.<br /><em>Keep perspective.</em></h2><p>Capture your draft, review what changed and decide what belongs in the final version.</p></div><div className="method-grid"><article className="method-card"><div className="method-card-icon"><UploadCloud size={18} /></div><span className="method-number">01 / 03</span><h3>Capture the version</h3><p>Start with a real upload, checksum, creator, and immutable revision history.</p><Link href="/register">Create a workspace <ArrowRight size={14} /></Link></article><article className="method-card featured"><div className="method-card-icon"><Network size={18} /></div><span className="method-number">02 / 03</span><h3>Connect the evidence</h3><p>Move from a finding to its text span, source, citation, claim, and explanation.</p><a href="#product">Explore the tools <ArrowRight size={14} /></a></article><article className="method-card" id="principles"><div className="method-card-icon"><ShieldCheck size={18} /></div><span className="method-number">03 / 03</span><h3>Keep people in the loop</h3><p>Uncertainty is a valid result. Editorial suggestions remain reviewable and provenance-safe.</p><Link href="/login">Sign in to review <ArrowRight size={14} /></Link></article></div></section>
    <section className="closing-section"><div className="closing-mark"><ShieldCheck size={20} /></div><h2>Evidence is the product.</h2><p>Give reviewers a clear trail and writers a responsible way forward.</p><Link className="button button-primary" href="/register">Open a workspace <ArrowRight size={16} /></Link></section>
    <footer className="public-footer"><div className="footer-brand"><AzaeronMark /></div><span>Evidence before interpretation.</span><div><Link href="/login">Sign in</Link><Link href="/register">Create workspace</Link></div></footer>
  </main>;
}
