"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CheckCircle2, FileCheck2, Fingerprint, LockKeyhole, Menu, Network, ShieldCheck, UploadCloud, X } from "lucide-react";
import { AzaeronMark } from "@/components/design-system";

const dimensions = ["Originality", "Similarity", "AI-writing signals", "Authorship consistency", "Citation integrity", "Source quality", "Provenance"];

export default function LandingPage() {
  const [mobileMenu, setMobileMenu] = useState(false);
  return <main className="azaeron-shell">
    <header className="public-nav"><div className="nav-inner"><Link href="/" className="brand-lockup" aria-label="Azaeron home"><AzaeronMark /></Link><button className="mobile-menu-button" onClick={() => setMobileMenu((open) => !open)} aria-label={mobileMenu ? "Close navigation" : "Open navigation"}>{mobileMenu ? <X size={19} /> : <Menu size={19} />}</button><nav className={`public-links ${mobileMenu ? "is-open" : ""}`} aria-label="Public navigation"><a href="#product" onClick={() => setMobileMenu(false)}>Product</a><a href="#method" onClick={() => setMobileMenu(false)}>Method</a><a href="#principles" onClick={() => setMobileMenu(false)}>Principles</a><Link href="/login">Sign in</Link><Link href="/register" className="nav-cta">Create workspace <ArrowRight size={14} /></Link></nav></div></header>
    <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Evidence-first writing intelligence <span className="eyebrow-version">VERITY</span></div><h1>Make every decision <em>defensible.</em></h1><p className="hero-lede">AZAERON turns document analysis into reviewable evidence: versioned text, independent dimensions, traceable findings, and responsible editorial support.</p><div className="hero-actions"><Link className="button button-primary" href="/register">Create a workspace <ArrowRight size={16} /></Link><Link className="button button-quiet" href="#method">See how it works <ArrowRight size={16} /></Link></div><div className="trust-line"><span><LockKeyhole size={14} /> workspace scoped</span><span><FileCheck2 size={14} /> evidence linked</span><span><Fingerprint size={14} /> version aware</span></div></div><div className="hero-art" aria-label="Evidence-first workspace preview"><div className="hero-art-grid" /><div className="hero-art-label"><span className="live-dot" /> WORKSPACE PREVIEW <span>NO SAMPLE DATA</span></div><div className="hero-score-card"><div className="score-card-top"><span>Analysis report</span><span className="score-status">EVIDENCE FIRST</span></div><div className="hero-preview-title">A clear trail from document to decision.</div><div className="hero-score-track" aria-hidden="true" /><div className="score-card-foot"><span>Confidence is shown only when recorded</span><strong>Reviewable</strong></div></div><div className="hero-float-card float-left"><Network size={16} /><span><strong>Graph</strong> traceability</span></div><div className="hero-float-card float-right"><CheckCircle2 size={15} /><span><strong>States</strong> explicit</span></div><div className="hero-art-footer"><span>01</span><span>VERSION</span><i /><span>04</span><span>EVIDENCE</span></div></div></section>
    <section className="workspace-section" id="product"><div className="section-kicker"><span>01</span> Product surface <i /></div><div className="section-heading-row"><div><h2>One workspace. Seven honest dimensions.</h2><p>Open a real document to inspect the evidence available for its immutable version.</p></div><div className="privacy-badge"><LockKeyhole size={15} /> No fabricated metrics</div></div><div className="workspace-frame"><div className="workspace-toolbar"><div className="mode-switch"><span className="active"><FileCheck2 size={15} /> Analysis report</span><span><Network size={15} /> Evidence graph</span></div><div className="toolbar-meta"><span className="status-pulse" /> Production state is explicit</div></div><div className="workspace-grid"><div className="editor-column"><div className="panel-heading"><div><span className="panel-eyebrow">DOCUMENT</span><strong>Versioned before it is analyzed</strong></div><UploadCloud size={18} className="text-teal-700" aria-hidden="true" /></div><div className="editor-wrap flex items-center justify-center px-7 text-center"><div><Fingerprint size={24} className="mx-auto text-teal-700" aria-hidden="true" /><p className="mt-3 text-sm font-semibold text-slate-700">Upload a real document</p><p className="mt-2 text-xs leading-5 text-slate-500">Its checksum, version, processing state, and analysis lineage stay connected.</p></div></div><div className="editor-footer"><span>PDF · DOCX · TXT · MD · HTML</span><Link href="/register"><span>Start in workspace <ArrowRight size={13} /></span></Link></div></div><div className="analysis-column"><div className="panel-heading"><div><span className="panel-eyebrow">EVIDENCE VIEW</span><strong>Available dimensions</strong></div><ShieldCheck size={18} className="text-teal-700" aria-hidden="true" /></div><div className="metric-grid">{dimensions.map((dimension) => <div className="metric-card" key={dimension}><div className="metric-card-top"><span>{dimension}</span><strong>State-based</strong></div><div className="metric-track" aria-hidden="true" /><p>Production, experimental, or insufficient evidence.</p></div>)}</div><div className="review-note"><FileCheck2 size={16} /><div><strong>Interpret with care</strong><p>Similarity is not plagiarism. A writing signal is not proof of AI use. Missing evidence remains visible.</p></div></div></div></div></div></section>
    <section className="method-section" id="method"><div className="section-kicker"><span>02</span> The method <i /></div><div className="method-heading"><h2>Useful for a first read.<br /><em>Honest enough for a final one.</em></h2><p>Every result carries its document version, evidence path, limitation, and recommended next action.</p></div><div className="method-grid"><article className="method-card"><div className="method-card-icon"><UploadCloud size={18} /></div><span className="method-number">01 / 03</span><h3>Capture the version</h3><p>Start with a real upload, checksum, creator, and immutable revision history.</p><Link href="/register">Create a workspace <ArrowRight size={14} /></Link></article><article className="method-card featured"><div className="method-card-icon"><Network size={18} /></div><span className="method-number">02 / 03</span><h3>Connect the evidence</h3><p>Move from a finding to its text span, source, citation, claim, and explanation.</p><a href="#product">View the model <ArrowRight size={14} /></a></article><article className="method-card" id="principles"><div className="method-card-icon"><ShieldCheck size={18} /></div><span className="method-number">03 / 03</span><h3>Keep people in the loop</h3><p>Uncertainty is a valid result. Editorial suggestions remain reviewable and provenance-safe.</p><Link href="/login">Sign in to review <ArrowRight size={14} /></Link></article></div></section>
    <section className="closing-section"><div className="closing-mark"><ShieldCheck size={20} /></div><h2>Evidence is the product.</h2><p>Give reviewers a clear trail and writers a responsible way forward.</p><Link className="button button-primary" href="/register">Open a workspace <ArrowRight size={16} /></Link></section>
    <footer className="public-footer"><div className="footer-brand"><AzaeronMark /></div><span>Evidence before interpretation.</span><div><Link href="/login">Sign in</Link><Link href="/register">Create workspace</Link></div></footer>
  </main>;
}
