apiVersion: 1

datasources:
  - name: Azaeron Prometheus
    uid: verity-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Azaeron Traces
    uid: verity-traces
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
