import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import { postWithRetryAfter } from "./live-request";

test("private agent: durable prompts, SSE unavailable state, edit, search, rename and deletion", async ({ page, baseURL }, testInfo) => {
  test.skip(process.env.RUN_LIVE_E2E !== "1", "Requires isolated PostgreSQL and worker");
  test.setTimeout(120_000);
  page.on("response", (response) => { if (response.status() === 429) console.warn(`[live-e2e] rate limited: ${new URL(response.url()).pathname}`); });
  const headers = { Origin: baseURL! };
  const credentials = { email: `agent-${Date.now()}@example.com`, password: randomUUID() + "Aa9!" };
  expect((await postWithRetryAfter(page.request, "/api/v1/auth/register", { headers, data: credentials })).status()).toBe(201);
  expect((await postWithRetryAfter(page.request, "/api/v1/auth/login", { headers, data: credentials })).ok()).toBeTruthy();
  expect((await page.request.post("/api/v1/auth/onboarding", { headers, data: { product_role: "researcher" } })).ok()).toBeTruthy();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/ai");
  await expect(page.getByText("Generation unavailable", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("azaeron-ai-workspace.png"), fullPage: true });
  const prompt = page.getByRole("textbox", { name: "Ask Azaeron AI" });
  await prompt.fill("My private writing question <script>alert('never execute')</script>");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByLabel("Azaeron AI conversation").getByRole("alert")).toContainText("unavailable", { timeout: 20_000 });
  await expect(page.getByLabel("Conversation messages")).toContainText("<script>");
  const list = await (await page.request.get("/api/v1/ai/conversations")).json();
  expect(list.items).toHaveLength(1);
  let detail = await (await page.request.get(`/api/v1/ai/conversations/${list.items[0].id}`)).json();
  expect(detail.runs[0].status).toBe("UNAVAILABLE");
  expect(detail.messages.filter((message: { role: string }) => message.role === "assistant")).toHaveLength(0);
  await page.reload();
  await page.getByRole("navigation", { name: "Conversation history" }).getByRole("button").first().click();
  await expect(page.getByLabel("Conversation messages")).toContainText("My private writing question");
  await page.getByRole("button", { name: "Edit prompt", exact: true }).click();
  await page.getByRole("textbox", { name: "Edit prompt and send a new turn" }).fill("An edited private question");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByLabel("Azaeron AI conversation").getByRole("alert")).toContainText("unavailable");
  detail = await (await page.request.get(`/api/v1/ai/conversations/${list.items[0].id}`)).json();
  expect(detail.messages).toHaveLength(2);
  expect(detail.messages[1].replaces_message_id).toBe(detail.messages[0].id);
  await page.getByText("Conversation options", { exact: true }).click();
  await page.getByRole("textbox", { name: "Conversation name" }).fill("Reviewed research conversation");
  await page.getByRole("button", { name: "Rename", exact: true }).click();
  await page.getByRole("textbox", { name: "Search conversations" }).fill("Reviewed research");
  await expect(page.getByRole("navigation", { name: "Conversation history" })).toContainText("Reviewed research conversation");
  // Home must read real actor-private history and deep-link the selected conversation.
  await page.goto("/dashboard");
  await page.getByRole("link", { name: "Reviewed research conversation", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/ai\\?conversation=${list.items[0].id}$`));
  await expect(page.getByLabel("Conversation messages")).toContainText("An edited private question");
  await page.getByText("Conversation options", { exact: true }).click();
  await page.getByText("Trust Drawer · recorded tools and model evidence", { exact: true }).click();
  await expect(page.getByText("verity-agent-1", { exact: false })).toBeVisible();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "Delete", exact: true }).click();
  await expect(page.getByLabel("Azaeron AI conversation").getByRole("status")).toContainText("Conversation deleted");
  expect((await page.request.get(`/api/v1/ai/conversations/${list.items[0].id}`)).status()).toBe(404);
});

test("agent document tool: pasted intake, grounded read, abstaining detection, no implicit revision", async ({ page, baseURL }) => {
  test.skip(process.env.RUN_LIVE_E2E !== "1", "Requires isolated storage and workers");
  test.setTimeout(120_000);
  page.on("response", (response) => { if (response.status() === 429) console.warn(`[live-e2e] rate limited: ${new URL(response.url()).pathname}`); });
  const headers = { Origin: baseURL! };
  const credentials = { email: `agent-doc-${Date.now()}@example.com`, password: randomUUID() + "Aa9!" };
  expect((await postWithRetryAfter(page.request, "/api/v1/auth/register", { headers, data: credentials })).status()).toBe(201);
  expect((await postWithRetryAfter(page.request, "/api/v1/auth/login", { headers, data: credentials })).ok()).toBeTruthy();
  expect((await page.request.post("/api/v1/auth/onboarding", { headers, data: { product_role: "researcher" } })).ok()).toBeTruthy();
  await page.goto("/ai");
  await page.getByText("Add context", { exact: true }).click();
  await page.getByText("Paste, type or upload", { exact: true }).click();
  await page.getByLabel("Text to analyse").fill("A private passage for the live agent tool test. It may support further review, but it does not prove authorship. " + "We write carefully and preserve sources for a later review. ".repeat(12));
  await page.getByRole("button", { name: "Use this text", exact: true }).click();
  await expect(page.getByText("Private version ready", { exact: true })).toBeVisible({ timeout: 60_000 });
  await page.getByRole("button", { name: "Read", exact: true }).click();
  await expect(page.getByText("document.read · recorded result", { exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(page.getByLabel("Conversation messages")).toContainText("A private passage for the live agent tool test.");
  await page.getByRole("button", { name: "Check AI", exact: true }).click();
  await expect(page.getByText("detection.analyze · recorded result", { exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(page.getByLabel("Conversation messages")).toContainText("Uncertain");
  await page.getByText("Voice", { exact: true }).click();
  await page.getByText("VoiceLock · optional writing style", { exact: true }).click();
  await page.getByRole("textbox", { name: "New profile name" }).fill("My reviewed sample");
  await page.getByRole("checkbox", { name: /I own and approve/ }).check();
  await page.getByRole("button", { name: "Create voice profile", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Writing voice" })).not.toHaveValue("");
  const profiles = await (await page.request.get("/api/v1/ai/voice-profiles")).json();
  expect(profiles.items).toHaveLength(1);
  expect(JSON.stringify(profiles.items[0].style)).not.toContain("We write carefully");
  await page.getByRole("button", { name: "Remove selected profile", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Writing voice" })).toHaveValue("");
  const docs = await (await page.request.get("/api/v1/documents")).json();
  const timeline = await (await page.request.get(`/api/v1/provenance/documents/${docs.items[0].id}/timeline`)).json();
  expect(timeline.versions).toHaveLength(1);
});
