service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http: {}
  jaeger_storage:
    backends:
      primary:
        badger:
          directories:
            keys: /tmp/badger-v2/key
            values: /tmp/badger-v2/data
          ephemeral: false
  jaeger_query:
    storage:
      traces: primary

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  jaeger_storage_exporter:
    trace_storage: primary
