export type Attachment = { document_id: string; document_version_id: string };
export type AgentTool = Attachment & { name: string; message_id?: string; voice_profile_id?: string; selection?: [number, number]; focus?: string; locked_spans?: Array<[number, number]> };
export type AgentMessage = { id: string; role: "user" | "assistant" | "tool"; content: string; sequence: number };
export type AgentRun = { id: string; message_id: string; status: string; error_code?: string; model_evidence: Record<string, unknown> };
export type Conversation = { id: string; title: string; messages: AgentMessage[]; runs: AgentRun[]; attachments: Attachment[]; tool_calls: Array<{ id: string; name: string; run_id: string; status: string; arguments: AgentTool }>; tool_results: Array<{ id: string; tool_call_id: string; content: Record<string, unknown> }> };
export type Receipt = { id: string; document_id: string; source_version_id: string; input_sha256: string; candidate_sha256: string; candidate_text: string; candidate_diff: string; policy_revision: string; decision: string; result_version_id: string | null; result_sha256: string | null; verification: { outcome: string; semantic_checked?: boolean; reasons?: string[]; limitations?: string[] }; model_evidence: Record<string, unknown>; tool_calls: Record<string, unknown>[]; protected_spans: Array<{ kind: string; value: string; start: number; end: number }>; similarity_before: Record<string, unknown> | null; similarity_after: Record<string, unknown> | null };
export const agentButton = "rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-50 hover:bg-teal-50 focus-visible:outline-2 focus-visible:outline-teal-700 dark:border-slate-600 dark:hover:bg-slate-800";
export const agentInput = "w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-600 dark:bg-slate-950";
export const isRunning = (run: AgentRun) => ["PENDING", "RUNNING"].includes(run.status);
